### ISSUE TITLE
Write a buffer that is not aligned to page start

### ISSUE THREAD

**Issue by heymikid** [lbthomsen/stm32-w25qxx#2]
Hi,

Thank you for writing this library and making it publicly available.

I have found a bug in your function w25qxx_write where I was trying to start writing in an address not aligned to a page start address, and the buffer was larger than what was left in the page (and had to continue to be written on the next page).

The calculation of the start_address, end_address was wrong in that case.

I don't know if you are maintaining this code, but here is my fix:

W25QXX_result_t w25qxx_write(W25QXX_HandleTypeDef *w25qxx, uint32_t address, uint8_t *buf, uint32_t len) {

    W25_DBG("w25qxx_write - address 0x%08lx len 0x%04lx", address, len);

    // Let's determine the pages
    uint32_t first_page = address / w25qxx->page_size;
    uint32_t last_page = (address + len - 1) / w25qxx->page_size;

    W25_DBG("w25qxx_write %lu pages from %lu to %lu", 1 + last_page - first_page, first_page, last_page);

    uint32_t buffer_offset = 0;
    uint32_t start_address = address;

    for (uint32_t page = first_page; page <= last_page; ++page) {

    	uint32_t write_len = w25qxx->page_size - (start_address & (w25qxx->page_size-1));
    	write_len = len > write_len ? write_len : len;

        W25_DBG("w25qxx_write: handling page %lu start_address = 0x%08lx buffer_offset = 0x%08lx len = %04lx", page, start_address,
                buffer_offset, write_len);

        // First wait for device to get ready
        if (w25qxx_wait_for_ready(w25qxx, HAL_MAX_DELAY) != W25QXX_Ok) {
            return W25QXX_Err;
        }

        if (w25qxx_write_enable(w25qxx) == W25QXX_Ok) {

            uint8_t tx[4] = {
            W25QXX_PAGE_PROGRAM, (uint8_t) (start_address >> 16), (uint8_t) (start_address >> 8), (uint8_t) (start_address), };

            cs_on(w25qxx);
            if (w25qxx_transmit(w25qxx, tx, 4) == W25QXX_Ok) { // size will always be fixed
                // Now write the buffer
                if (w25qxx_transmit(w25qxx, buf+buffer_offset, write_len) != W25QXX_Ok) {
                    cs_off(w25qxx);
                    return W25QXX_Err;
                }
            }
            cs_off(w25qxx);
        }
        start_address += write_len;
        buffer_offset += write_len;
        len -= write_len;
    }

    return W25QXX_Ok;
}

**Comment by lbthomsen** [comment]
Let me have a look and thank you for the comment.  I am sure there are other bugs in there :)

**Comment by lbthomsen** [comment]
Ok - added your code looks ok.
